version: '3.5'

services:
  nginx-php-service:
    container_name: nginx-php-service
    image: nginx:1.24
    restart: no
    ports:
      - "80:80"
    volumes:
      - .:/var/www/
      - ./.docker/config/nginx/:/etc/nginx/conf.d/
    networks:
      - net-php-service

  php-php-service:
    build:
      context: ./.docker/
    container_name: php-php-service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - net-php-service

networks:
  net-php-service:
    name: net-php-service